class Enums::HHAConcept < Enums::BaseEnum
  description "The Happy Home Academy \"concepts\" to which items can belong."

  value "AMUSEMENT_PARK", value: "amusement park"
  value "ANCIENT", value: "ancient"
  value "APPAREL_SHOP", value: "apparel shop"
  value "ARCADE", value: "arcade"
  value "BATHROOM", value: "bathroom"
  value "CAFE", value: "café"
  value "CHILDS_ROOM", value: "child's room"
  value "CITY_LIFE", value: "city life"
  value "CONCERT", value: "concert"
  value "CONSTRUCTION_SITE", value: "construction site"
  value "DEN", value: "den"
  value "EUROPEAN", value: "European"
  value "EXPENSIVE", value: "expensive"
  value "FACILITY", value: "facility"
  value "FANCY", value: "fancy"
  value "FANTASY", value: "fantasy"
  value "FITNESS", value: "fitness"
  value "FREEZING_COLD", value: "freezing cold"
  value "GARDEN", value: "garden"
  value "HARMONIOUS", value: "harmonious"
  value "HERITAGE", value: "heritage"
  value "HORROR", value: "horror"
  value "HOSPITAL", value: "hospital"
  value "KITCHEN", value: "kitchen"
  value "LAB", value: "lab"
  value "LIVING_ROOM", value: "living room"
  value "LOCAL", value: "local"
  value "MUSIC", value: "music"
  value "NATURE", value: "nature"
  value "OCEAN", value: "ocean"
  value "OFFICE", value: "office"
  value "OUTDOORS", value: "outdoors"
  value "PARK", value: "park"
  value "PARTY", value: "party"
  value "PUBLIC_BATH", value: "public bath"
  value "RESORT", value: "resort"
  value "RESTAURANT", value: "restaurant"
  value "RETRO", value: "retro"
  value "SCHOOL", value: "school"
  value "SCIENCE_FICTION", value: "sci-fi"
  value "SHOP", value: "shop"
  value "SPACE", value: "space"
  value "SPORTS", value: "sports"
  value "STYLISH", value: "stylish"
  value "SUPERMARKET", value: "supermarket"
  value "WORKSHOP", value: "workshop"
end
