class Enums::HHASeries < Enums::BaseEnum
  description "The Happy Home Academy \"series\" in which items can belong."

  value "ANTIQUE", value: "antique"
  value "BAMBOO", value: "bamboo"
  value "BUNNY_DAY", value: "Bunny Day"
  value "CARDBOARD", value: "cardboard"
  value "CHERRY_BLOSSOMS", value: "cherry blossoms"
  value "CINNAMON_ROLL", value: "Cinnamoroll"
  value "COOL", value: "cool"
  value "CUTE", value: "cute"
  value "DINER", value: "diner"
  value "DREAMY", value: "dreamy"
  value "ELEGANT", value: "elegant"
  value "FESTIVALE", value: "Festivale"
  value "FESTIVE", value: "festive"
  value "FLOWERS", value: "flowers"
  value "FROZEN", value: "frozen"
  value "FRUITS", value: "fruits"
  value "GOLDEN", value: "golden"
  value "HELLO_KITTY", value: "Hello Kitty"
  value "IMPERIAL", value: "imperial"
  value "IRON", value: "iron"
  value "IRONWOOD", value: "ironwood"
  value "KEROKEROKEROPPI", value: "Kerokerokeroppi"
  value "KIKI_AND_LALA", value: "Kiki & Lala"
  value "LOG", value: "log"
  value "MARIO", value: "Mario"
  value "MERMAID", value: "Moroccan"
  value "MOROCCAN", value: "mermaid"
  value "MOTHERLY", value: "motherly"
  value "MUSH", value: "mush"
  value "MY_MELODY", value: "My Melody"
  value "NORDIC", value: "Nordic"
  value "PATCHWORK", value: "patchwork"
  value "PIRATE", value: "pirate"
  value "PLAZA", value: "plaza"
  value "POMPOMPURIN", value: "Pompompurin"
  value "RANCH", value: "ranch"
  value "RATTAN", value: "rattan"
  value "SHELL", value: "shell"
  value "SIMPLE", value: "simple"
  value "SLOPPY", value: "sloppy"
  value "SPOOKY", value: "spooky"
  value "STARS", value: "stars"
  value "THROWBACK", value: "throwback"
  value "TREES_BOUNTY_OR_LEAVES", value: "tree's bounty or leaves"
  value "TURKEY_DAY", value: "Turkey Day"
  value "VINTAGE", value: "vintage"
  value "WEDDING", value: "wedding"
  value "WOODEN", value: "wooden"
  value "WOODEN_BLOCK", value: "wooden block"
end
