class Enums::HHASet < Enums::BaseEnum
  description "The Happy Home Academy \"furniture sets\" in which items can belong."

  value "APPLE", value: "apple"
  value "ARTSY", value: "artsy"
  value "BEAR", value: "bear"
  value "BIRTHDAY", value: "birthday"
  value "BUG_HEAD", value: "bug head"
  value "CASTLE", value: "castle"
  value "CHALKBOARD", value: "chalkboard"
  value "CHERRY", value: "cherry"
  value "DEN", value: "den"
  value "GAMING", value: "gaming"
  value "GARDEN", value: "garden"
  value "IMPERIAL_DINING", value: "imperial dining"
  value "IRON_GARDEN", value: "iron garden"
  value "KITCHEN", value: "kitchen"
  value "LECTURE_HALL", value: "lecture hall"
  value "METAL_AND_WOOD", value: "metal and wood"
  value "NATURAL", value: "natural"
  value "OFFICE", value: "office"
  value "ORANGE", value: "orange"
  value "PANDA", value: "panda"
  value "PEACH", value: "peach"
  value "PEAR", value: "pear"
  value "PET", value: "pet"
  value "RUINED", value: "ruined"
  value "SCHOOL", value: "school"
  value "SPORTS_RING", value: "sports ring"
  value "STANDEE", value: "standee"
  value "STONE", value: "stone"
  value "STUDY", value: "study"
end
