class Enums::Species < Enums::BaseEnum
  description "A list of animal species that each Villager can belong to."

  value "ALLIGATOR", value: "Alligator"
  value "ANTEATER", value: "Anteater"
  value "BEAR", value: "Bear"
  value "BEAR_CUB", value: "Bear cub"
  value "BIRD", value: "Bird"
  value "BULL", value: "Bull"
  value "CAT", value: "Cat"
  value "CHICKEN", value: "Chicken"
  value "COW", value: "Cow"
  value "DEER", value: "Deer"
  value "DOG", value: "Dog"
  value "DUCK", value: "Duck"
  value "EAGLE", value: "Eagle"
  value "ELEPHANT", value: "Elephant"
  value "FROG", value: "Frog"
  # No Giraffes 😔
  value "GOAT", value: "Goat"
  value "GORILLA", value: "Gorilla"
  value "HAMSTER", value: "Hamster"
  value "HIPPO", value: "Hippo"
  value "HORSE", value: "Horse"
  value "KANGAROO", value: "Kangaroo"
  value "KOALA", value: "Koala"
  value "LION", value: "Lion"
  value "MONKEY", value: "Monkey"
  value "MOUSE", value: "Mouse"
  value "OCTOPUS", value: "Octopus"
  value "OSTRICH", value: "Ostrich"
  value "PENGUIN", value: "Penguin"
  value "PIG", value: "Pig"
  value "RABBIT", value: "Rabbit"
  value "RHINOCEROS", value: "Rhinoceros"
  value "SHEEP", value: "Sheep"
  value "SQUIRREL", value: "Squirrel"
  value "TIGER", value: "Tiger"
  value "WOLF", value: "Wolf"
end
